/**
 * Code generator that reads Infrahub schema definitions and produces
 * typed TypeScript interfaces and helper types.
 *
 * Design goals:
 * - Deterministic output: sorted fields, stable filenames
 * - One file per schema kind + an index barrel
 * - Generated interfaces integrate with InfrahubClient via a typed helper
 */

import type {
  SchemaType,
  NodeSchema,
  GenericSchema,
  AttributeSchema,
  RelationshipSchema,
} from "../schema/types.js";
import { isNodeSchema } from "../schema/types.js";
import { getTsType, kindToTypeName, kindToFilename } from "./type-map.js";

/** Schema export format — matches what SchemaManager.exportSchema() returns. */
export interface SchemaExportData {
  nodes?: NodeSchema[];
  generics?: GenericSchema[];
}

/** A single generated file. */
export interface GeneratedFile {
  /** Relative filename (e.g. "infra-device.ts") */
  filename: string;
  /** Full generated source code */
  content: string;
  /** The schema kind this was generated from */
  kind: string;
}

/** Options for the code generator. */
export interface GeneratorOptions {
  /** Header comment to prepend to each file. Default: auto-generated warning. */
  header?: string;
  /** Whether to generate generic schemas (default: true). */
  includeGenerics?: boolean;
}

const DEFAULT_HEADER = `// This file was auto-generated by infrahub-sdk codegen.
// Do not edit manually.
`;

/**
 * Generate TypeScript source files from an Infrahub schema export.
 *
 * Returns an array of GeneratedFile objects (one per schema + index barrel).
 * Output is deterministic: schemas sorted by kind, fields sorted by name.
 */
export function generateFromSchema(
  data: SchemaExportData,
  options: GeneratorOptions = {},
): GeneratedFile[] {
  const header = options.header ?? DEFAULT_HEADER;
  const includeGenerics = options.includeGenerics ?? true;

  // Collect all schemas, sorted by kind for determinism
  const schemas: SchemaType[] = [];
  if (data.nodes) {
    schemas.push(...data.nodes);
  }
  if (includeGenerics && data.generics) {
    schemas.push(...data.generics);
  }
  schemas.sort((a, b) => a.kind.localeCompare(b.kind));

  // Build a set of all known kinds for relationship peer references
  const knownKinds = new Set(schemas.map((s) => s.kind));

  // Generate one file per schema
  const files: GeneratedFile[] = schemas.map((schema) =>
    generateSchemaFile(schema, knownKinds, header),
  );

  // Generate index barrel
  files.push(generateIndexFile(schemas, header));

  // Generate the typed-client helper
  files.push(generateTypedClientFile(schemas, header));

  return files;
}

/** Generate a single schema file with interface + create-data type. */
function generateSchemaFile(
  schema: SchemaType,
  knownKinds: Set<string>,
  header: string,
): GeneratedFile {
  const typeName = kindToTypeName(schema.kind);
  const filename = `${kindToFilename(schema.kind)}.ts`;

  // Collect imports needed for relationship peer types
  const peerImports = collectPeerImports(schema, knownKinds);

  const lines: string[] = [header];

  // Add peer imports
  for (const [peerKind, peerType] of sortedEntries(peerImports)) {
    const peerFile = `./${kindToFilename(peerKind)}.js`;
    lines.push(`import type { ${peerType}Data } from "${peerFile}";`);
  }
  if (peerImports.size > 0) {
    lines.push("");
  }

  // JSDoc for the interface
  if (schema.description) {
    lines.push(`/** ${schema.description} */`);
  }

  // Main interface — represents a fetched node with full attribute metadata
  lines.push(`export interface ${typeName} {`);
  lines.push(`  /** Unique identifier */`);
  lines.push(`  id: string;`);
  lines.push(`  /** Display label */`);
  display_label: lines.push(`  display_label: string | null;`);

  // Attributes — sorted by name
  const sortedAttrs = [...schema.attributes].sort((a, b) =>
    a.name.localeCompare(b.name),
  );
  for (const attr of sortedAttrs) {
    lines.push(...generateAttributeField(attr));
  }

  // Relationships — sorted by name
  const sortedRels = [...schema.relationships].sort((a, b) =>
    a.name.localeCompare(b.name),
  );
  for (const rel of sortedRels) {
    lines.push(...generateRelationshipField(rel, knownKinds));
  }

  lines.push(`}`);
  lines.push("");

  // Create-data interface — for creating new nodes
  lines.push(`/** Input data for creating a new ${typeName}. */`);
  lines.push(`export interface ${typeName}Create {`);
  for (const attr of sortedAttrs) {
    lines.push(...generateCreateField(attr));
  }
  for (const rel of sortedRels) {
    lines.push(...generateCreateRelField(rel, knownKinds));
  }
  lines.push(`}`);
  lines.push("");

  // Data type alias — for use in relationship references
  lines.push(`/** Reference data for ${typeName} in relationships. */`);
  lines.push(`export interface ${typeName}Data {`);
  lines.push(`  id?: string;`);
  lines.push(`  hfid?: string[];`);
  lines.push(`}`);
  lines.push("");

  // Kind constant
  lines.push(`/** The schema kind string for ${typeName}. */`);
  lines.push(`export const ${typeName}Kind = "${schema.kind}" as const;`);
  lines.push("");

  return { filename, content: lines.join("\n"), kind: schema.kind };
}

/** Generate the attribute field lines for the main interface. */
function generateAttributeField(attr: AttributeSchema): string[] {
  const tsType = getTsType(attr.kind);
  const optional = attr.optional ? "?" : "";
  const lines: string[] = [];

  // Build JSDoc
  const docParts: string[] = [];
  if (attr.label) docParts.push(attr.label);
  if (attr.description) docParts.push(attr.description);
  if (attr.kind === "Dropdown" && attr.enum) {
    docParts.push(`Values: ${attr.enum.join(", ")}`);
  }
  if (attr.read_only) docParts.push("(read-only)");

  if (docParts.length > 0) {
    lines.push(`  /** ${docParts.join(" — ")} */`);
  }

  // Use enum union type for Dropdown with enum values
  if (attr.kind === "Dropdown" && attr.enum && attr.enum.length > 0) {
    const unionType = attr.enum.map((v) => `"${v}"`).join(" | ");
    lines.push(`  ${attr.name}${optional}: ${unionType};`);
  } else {
    lines.push(`  ${attr.name}${optional}: ${tsType};`);
  }

  return lines;
}

/** Generate a relationship field for the main interface. */
function generateRelationshipField(
  rel: RelationshipSchema,
  knownKinds: Set<string>,
): string[] {
  const lines: string[] = [];
  const peerType = knownKinds.has(rel.peer)
    ? kindToTypeName(rel.peer)
    : "{ id: string }";
  const optional = rel.optional ? "?" : "";

  const docParts: string[] = [];
  if (rel.label) docParts.push(rel.label);
  if (rel.description) docParts.push(rel.description);
  if (rel.read_only) docParts.push("(read-only)");
  docParts.push(`Peer: ${rel.peer}`);

  if (docParts.length > 0) {
    lines.push(`  /** ${docParts.join(" — ")} */`);
  }

  if (rel.cardinality === "one") {
    lines.push(`  ${rel.name}${optional}: ${peerType} | null;`);
  } else {
    lines.push(`  ${rel.name}${optional}: ${peerType}[];`);
  }

  return lines;
}

/** Generate a create-data field for an attribute. */
function generateCreateField(attr: AttributeSchema): string[] {
  if (attr.read_only) return [];

  const tsType = getTsType(attr.kind);
  const optional = attr.optional ? "?" : "";

  if (attr.kind === "Dropdown" && attr.enum && attr.enum.length > 0) {
    const unionType = attr.enum.map((v) => `"${v}"`).join(" | ");
    return [`  ${attr.name}${optional}: ${unionType};`];
  }

  return [`  ${attr.name}${optional}: ${tsType};`];
}

/** Generate a create-data field for a relationship. */
function generateCreateRelField(
  rel: RelationshipSchema,
  knownKinds: Set<string>,
): string[] {
  if (rel.read_only) return [];

  const optional = rel.optional ? "?" : "";
  const peerDataType = knownKinds.has(rel.peer)
    ? `${kindToTypeName(rel.peer)}Data`
    : "{ id?: string; hfid?: string[] }";

  if (rel.cardinality === "one") {
    return [`  ${rel.name}${optional}: ${peerDataType} | string;`];
  }
  return [`  ${rel.name}${optional}: (${peerDataType} | string)[];`];
}

/** Generate the index barrel file. */
function generateIndexFile(
  schemas: SchemaType[],
  header: string,
): GeneratedFile {
  const lines: string[] = [header];

  for (const schema of schemas) {
    const typeName = kindToTypeName(schema.kind);
    const file = `./${kindToFilename(schema.kind)}.js`;
    lines.push(
      `export type { ${typeName}, ${typeName}Create, ${typeName}Data } from "${file}";`,
    );
    lines.push(`export { ${typeName}Kind } from "${file}";`);
  }

  lines.push("");
  lines.push(`export type { TypedInfrahubClient } from "./typed-client.js";`);
  lines.push(
    `export { createTypedClient, kindMap } from "./typed-client.js";`,
  );
  lines.push("");

  return { filename: "index.ts", content: lines.join("\n"), kind: "__index__" };
}

/** Generate the typed-client helper. */
function generateTypedClientFile(
  schemas: SchemaType[],
  header: string,
): GeneratedFile {
  const nodeSchemas = schemas.filter(isNodeSchema);
  const lines: string[] = [header];

  lines.push(`import type { InfrahubClient } from "../client.js";`);
  lines.push(`import type { InfrahubNode } from "../node/index.js";`);
  lines.push("");

  // Import all generated types
  for (const schema of nodeSchemas) {
    const typeName = kindToTypeName(schema.kind);
    const file = `./${kindToFilename(schema.kind)}.js`;
    lines.push(
      `import type { ${typeName}Create } from "${file}";`,
    );
  }
  lines.push("");

  // Kind-to-type mapping
  lines.push(`/** Map of schema kind strings to their type names. */`);
  lines.push(`export const kindMap: Record<string, string> = {`);
  for (const schema of nodeSchemas) {
    lines.push(`  "${schema.kind}": "${kindToTypeName(schema.kind)}",`);
  }
  lines.push(`};`);
  lines.push("");

  // Typed client interface — provides type-safe create/get/all
  lines.push(`/** Typed wrapper around InfrahubClient with schema-aware methods. */`);
  lines.push(`export interface TypedInfrahubClient {`);
  lines.push(`  /** The underlying InfrahubClient instance. */`);
  lines.push(`  client: InfrahubClient;`);
  lines.push("");

  for (const schema of nodeSchemas) {
    const typeName = kindToTypeName(schema.kind);
    lines.push(`  /** Operations for ${schema.kind} nodes. */`);
    lines.push(`  ${lcFirst(schema.name)}: {`);
    lines.push(
      `    create(data: ${typeName}Create): Promise<InfrahubNode>;`,
    );
    lines.push(
      `    get(options: { id?: string; hfid?: string[]; [key: string]: unknown }): Promise<InfrahubNode>;`,
    );
    lines.push(
      `    all(options?: { offset?: number; limit?: number; filters?: Record<string, unknown> }): Promise<InfrahubNode[]>;`,
    );
    lines.push(
      `    count(options?: Record<string, unknown>): Promise<number>;`,
    );
    lines.push(
      `    delete(id: string): Promise<void>;`,
    );
    lines.push(`  };`);
  }

  lines.push(`}`);
  lines.push("");

  // Factory function
  lines.push(`/** Create a typed client wrapper from an InfrahubClient. */`);
  lines.push(`export function createTypedClient(client: InfrahubClient): TypedInfrahubClient {`);
  lines.push(`  return {`);
  lines.push(`    client,`);
  for (const schema of nodeSchemas) {
    const kind = schema.kind;
    lines.push(`    ${lcFirst(schema.name)}: {`);
    lines.push(
      `      create: (data) => client.create("${kind}", data as Record<string, unknown>),`,
    );
    lines.push(
      `      get: (options) => client.get("${kind}", options),`,
    );
    lines.push(
      `      all: (options) => client.all("${kind}", options ?? {}),`,
    );
    lines.push(
      `      count: (options) => client.count("${kind}", options ?? {}),`,
    );
    lines.push(
      `      delete: (id) => client.delete("${kind}", id),`,
    );
    lines.push(`    },`);
  }
  lines.push(`  };`);
  lines.push(`}`);
  lines.push("");

  return {
    filename: "typed-client.ts",
    content: lines.join("\n"),
    kind: "__typed_client__",
  };
}

/** Collect peer types that need to be imported. */
function collectPeerImports(
  schema: SchemaType,
  knownKinds: Set<string>,
): Map<string, string> {
  const imports = new Map<string, string>();
  for (const rel of schema.relationships) {
    if (knownKinds.has(rel.peer) && rel.peer !== schema.kind) {
      imports.set(rel.peer, kindToTypeName(rel.peer));
    }
  }
  return imports;
}

/** Return sorted entries of a map. */
function sortedEntries<V>(map: Map<string, V>): [string, V][] {
  return [...map.entries()].sort(([a], [b]) => a.localeCompare(b));
}

/** Lowercase first character of a string. */
function lcFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}
